### ISSUE TITLE
Constant Rate Factor?

### ISSUE THREAD

**Issue by jtkeyva** [chipweinberger/flutter_quick_video_encoder#2]
Hello, wondering if there are any plans for CRF or something similar? Maybe it's' not supported?

https://unix.stackexchange.com/questions/28803/how-can-i-reduce-a-videos-size-with-ffmpeg

Additional options that might be worth considering is setting the [Constant Rate Factor](https://slhck.info/video/2017/02/24/crf-guide.html), which lowers the average bit rate, but retains better quality. Vary the CRF between around 18 and 24 — the lower, the higher the bitrate.

ffmpeg -i input.mp4 -vcodec libx264 -crf 20 output.mp4

**Comment by chipweinberger** [comment]
sure, open a PR. not sure if supported.

**Comment by jtkeyva** [comment]
sorry i have no idea how your underlying encoder works or if crf is even doable.  looks to work in x264, x265 and libvpx but not sure if that's what yours uses?

**Comment by chipweinberger** [comment]
the code is all open source.

look at /android and /ios

that should give you a good understanding

**Comment by jtkeyva** [comment]
it's beyond me...i'm gonna run some file size tests as I would love this to be a viable encoding option. thanks for your work on this :)

**Comment by chipweinberger** [comment]
with some googling there is no CRF option

we use AVFoundation on iOS and MediaCodec on Android

**Comment by jtkeyva** [comment]
ahhh thanks for that :)
