### ISSUE TITLE
Feature Request: Video Frame Extraction From Input Video Source and Manipulation Frame Image 


### ISSUE THREAD

**Issue by Greek-Cp** [chipweinberger/flutter_quick_video_encoder#6]
I suggest adding a feature for video file input where all video frames will be extracted so developers can manipulate and edit each frame individually. This will allow for adding text subtitle animations to specific frames. For example, subtitles can be added as sequential image animations like Subtitle_1.png, Subtitle_2.png, up to Subtitle_1000.png. These subtitle frames will then be rendered simultaneously with the video frames, overlaying the subtitle frames on top of the video frames. Additionally, this feature will facilitate the application of video filters on a frame-by-frame basis, providing more flexibility in video editing."

**Comment by Greek-Cp** [comment]
Hi  @chipweinberger, 

I recently conducted an experiment to extract all frames from a video source input sent via Flutter to a native function extractFrameVideo. I extracted the frames in their entirety and created a function to extract each frame and send it as raw RGBA to the Flutter code. Subsequently, I used your library to render the frame segments from my video source and successfully exported it as an MP4.

I suggest adding a feature for video file input where all video frames will be extracted so developers can manipulate and edit each frame individually. This will allow for adding text subtitle animations to specific frames. For example, subtitles can be added as sequential image animations like Subtitle_1.png, Subtitle_2.png, up to Subtitle_1000.png. These subtitle frames will then be rendered simultaneously with the video frames, overlaying the subtitle frames on top of the video frames. Additionally, this feature will facilitate the application of video filters on a frame-by-frame basis, providing more flexibility in video editing.

Thank you for considering this enhancement.

**Comment by chipweinberger** [comment]
thanks for the idea

it is beyond the scope of this library

`flutter_quick_video_encoder` is just for encoding, not decoding

**Comment by Greek-Cp** [comment]
> thanks for the idea
> 
> it is beyond the scope of this library
> 
> `flutter_quick_video_encoder` is just for encoding, not decoding
> 

Can you add this feature or library?  if possible that would be good, because it will be used by many developers and there is very little library information to do this frame video Manipulation

**Comment by chipweinberger** [comment]
I cannot add it, no. 

But you can create a new library and add it.
