### ISSUE TITLE
AVAssetWriterInput is not initialized

### ISSUE THREAD

**Issue by anirudhrao-github** [chipweinberger/flutter_quick_video_encoder#7]
Getting Platform exception when  
 `await FlutterQuickVideoEncoder.appendVideoFrame(rgbaFrame);`
 
 Error:
```
PlatformException(AVAssetWriterInputUnavailable, AVAssetWriterInput is not initialized, null, null)
[log] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
      #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
      <asynchronous suspension>
      #2      FlutterQuickVideoEncoder._invokeMethod (package:flutter_quick_video_encoder/flutter_quick_video_encoder.dart:134:18)
      <asynchronous suspension>
      #3      FlutterQuickVideoEncoder.appendVideoFrame (package:flutter_quick_video_encoder/flutter_quick_video_encoder.dart:84:12)
      <asynchronous suspension>
```
Here is the initialization: (Initialized and used inside a worker isolate)
```
await FlutterQuickVideoEncoder.setup(
    width:
        Platform.isIOS ? cameraImages.first.width : cameraImages.first.height,
    height:
        Platform.isIOS ? cameraImages.first.height : cameraImages.first.width,
    fps: 30,
    videoBitrate: 1000000,
    profileLevel: ProfileLevel.any,
    audioBitrate: 0,
    audioChannels: 0,
    sampleRate: 0,
    filepath: filepath,
  );

```      

I am using this to generate video from List<CameraImage>
On android it is working fine

Please check and guide me with solution

Thanks in advance

**Comment by chipweinberger** [comment]
probably cameraImages.first.height or cameraImages.first.width is zero

does example work?

**Comment by anirudhrao-github** [comment]
Thanks for the quick reply

I am getting that error not once but multiple times.

Say if there are 60 frames, I get this error for atleast 10 frames.

I might be wrong but If the cameraImages.first.height or cameraImages.first.width is zero, it should give error for all the frames right?

**Comment by chipweinberger** [comment]
sounds like you are not using "await setup" properly. make sure it finishes first.

does the example work?

**Comment by anirudhrao-github** [comment]
As shared in my initial comment, I have awaited all the 3 methods
1. Setup method
2. Append method
3. Finish method

Here is the flow
1. Start Video recording (from camera plugin)
2. From the onAvailable callback (startVideoRecording), add the frame (CameraImage) to a list (`List<CameraImage>`)
3. Stop Video recording
4. Pass the CameraImages list to an isolate using compute function
5. In the isolate, first ensure BackgroundIsolateBinaryMessenger initialized and pass the root isolate token
6. await setup method of the FlutterQuickVideoEncoder
7. Convert the CameraImage list to rgba list. (`List<CameraImage>` to `List<Uint8List>`)
8. Append this rgba image to FlutterQuickVideoEncoder using the append method (await the operation)
9. After appending all the frames, await FlutterQuickVideoEncoder.finish()

I am getting the error on calling FlutterQuickVideoEncoder.append() on some of the frames but not all.
On calling finish() I am able to generate the video but the errors make it inconsistent.

On Android the flow works fine.

Please let me know if I need to change something to fix this.

**Comment by chipweinberger** [comment]
does the example app work?

**Comment by anirudhrao-github** [comment]
Checked with the example. It indeed works.
Found out the issue was due to empty plane[0] bytes on iOS.

Thanks a lot for the help

**Comment by chipweinberger** [comment]
why was it empty?

could i improve the errors?

**Comment by anirudhrao-github** [comment]
> why was it empty?


It was having multiple empty frames not sure why. I was using `startVideoRecording(onAvailable)`
It was fine when i switched to `startImageStream`

> could i improve the errors?


The `appendVideoFrame` method was showing log with 0 bytes and occasionally i was getting the `AssertionError` of bytes length not equal to `width * height * 4` but it was not consistent.
An error for adding empty frame would help.
